version: 2
workflows:
  version: 2
  build-deploy:
    jobs:
      - integration
jobs:
  integration:
    docker:
      - image: "circleci/node:10.14.1"
    steps:
      - checkout
      - restore_cache:
          keys:
            # when lock file changes, use increasingly general patterns to restore cache
            - node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - node-v1-{{ .Branch }}-
            - node-v1-
      - run:
          name: Install packages from lockfile
          command: npm ci
      - run:
          name: Tests and coverage
          command: "npx mkdirp test-results && npm run -s test -- --coverage-report=lcovonly --reporter=xunit > ./test-results/camelspaceTests.xml"
      - save_cache:
          paths:
            - ~/usr/local/lib/node_modules # location depends on npm version
          key: node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - store_test_results:
          path: "test-results"
      - store_artifacts:
          path: "coverage"
