version: 2
workflows:
  version: 2
  build-deploy:
    jobs:
      - integration
jobs:
  integration:
    docker:
      - image: "circleci/node:10.14.1"
    steps:
      - checkout
      - restore_cache:
          keys:
            # when lock file changes, use increasingly general patterns to restore cache
            - node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - node-v1-{{ .Branch }}-
            - node-v1-
      - run:
          name: Install packages from lockfile
          command: npm ci
      - run:
          name: Test suites
          command: "npm run -s format && mkdir -p test-results && npm run -s tap -- --reporter=xunit --no-coverage > ./test-results/camelspaceTests.xml"
      - run:
          name: Code coverage
          command: npm run -s tap && npx codecov
      - save_cache:
          paths:
            - ~/usr/local/lib/node_modules # location depends on npm version
          key: node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - store_test_results:
          path: "test-results"
